name: Build Tests

on: [push, pull_request]

jobs:
  wait-for-build:
    name: Waiting for build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.8.0
        with:
          ref: ${{ github.ref }}
          check-name: 'Building JSS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
        if: github.event_name == 'push'

      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.8.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Building JSS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
        if: github.event_name == 'pull_request'

  debian-test:
    name: Debian Build Test
    uses: ./.github/workflows/debian-test.yml

  fedora-test:
    name: Fedora Build Test
    needs: wait-for-build
    uses: ./.github/workflows/fedora-test.yml

  symbol-test:
    name: Symbol Test
    uses: ./.github/workflows/symbol-test.yml

  rpm-test:
    name: RPM Test
    needs: wait-for-build
    uses: ./.github/workflows/rpm-test.yml

  sandbox-test:
    name: Sandbox Test
    needs: wait-for-build
    uses: ./.github/workflows/sandbox-test.yml

  version-number-test:
    name: Version number
    uses: ./.github/workflows/version-number-test.yml
