name: Debian Build Test

on: workflow_call

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - 'debian:testing'
          - 'ubuntu:rolling'
    container: ${{ matrix.os }}
    env:
      SHARED: /tmp/workdir/jss
    steps:
    - name: Clone repository
      uses: actions/checkout@v7

    - name: Set up Java
      uses: actions/setup-java@v5
      with:
        java-version: '25'
        distribution: 'adopt'

    - name: Install dependencies
      run: |
        apt-get update

        # https://salsa.debian.org/freeipa-team/jss/-/blob/master/debian/control
        apt-get install -y \
            cmake \
            g++ \
            junit5 \
            libcommons-lang3-java \
            libnss3-dev \
            libnss3-tools \
            libopentest4j-java \
            libslf4j-java \
            maven \
            openjdk-25-jdk \
            unzip \
            zip

    - name: Build with CMake
      run: ./build.sh

    - name: Build with Maven
      run: mvn --batch-mode package

    - name: Compare jss.jar
      run: |
        jar tvf ~/build/jss/jss.jar \
            | awk '{print $8;}' \
            | sort \
            | grep -v '/$' \
            | tee cmake.out
        jar tvf base/target/jss.jar \
            | awk '{print $8;}' \
            | sort \
            | grep -v '/$' \
            | grep -v '^META-INF/maven/' \
            | tee maven.out
        diff cmake.out maven.out

    # TODO: Run examples
