name: PKI Tests

on:
  workflow_run:
    workflows: ['Build JSS']
    types:
      - completed

jobs:
  pki-build-test:
    name: Testing PKI build
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pki-build-test.yml

  pki-tools-test:
    name: Testing PKI tools
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pki-tools-test.yml

  pki-ca-test:
    name: Testing PKI CA
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pki-ca-test.yml

  pki-tps-test:
    name: Testing PKI TPS
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/pki-tps-test.yml
