name: Tomcat Tests

on: [push, pull_request]

jobs:
  build:
    name: Waiting for build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.ref }}
          check-name: 'Building JSS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
        if: github.event_name == 'push'

      - name: Wait for build
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: 'Building JSS'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 30
        if: github.event_name == 'pull_request'

  https-test:
    name: Testing basic HTTPS
    needs: build
    uses: ./.github/workflows/tomcat-https-test.yml

  https-protocols-test:
    name: Testing HTTPS protocols
    needs: build
    uses: ./.github/workflows/tomcat-https-protocols-test.yml
